// data/aiToolsWithWeb3.ts
export interface AITool {
  id: number;
  name: string;
  handle: string;
  website: string;
  description: string;
  category: string;
  free: boolean;
  openSource: boolean;
  blockchain?: boolean;
  privacy?: boolean;
  web3?: boolean;
  verified?: boolean;
}

export const aiTools: AITool[] = [
  {
    id: 1,
    name: "LM Arena",
    handle: "lm-arena",
    website: "https://lmarena.ai",
    description: "Community-driven platform to compare and evaluate LLMs with anonymous head-to-head battles and leaderboards.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 2,
    name: "Cocoon (TON Blockchain)",
    handle: "cocoon-tg",
    website: "https://cocoon.tg",
    description: "Decentralized AI network on TON blockchain. AI models run privately using distributed GPUs with confidential computing and TON token rewards.",
    category: "Private AI",
    free: true,
    openSource: true,
    blockchain: true,
    privacy: true,
    web3: true,
  },
  {
    id: 3,
    name: "Qwen (Alibaba)",
    handle: "qwen",
    website: "https://qwenlm.ai",
    description: "Open-source large language models from Alibaba for research and production use.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 4,
    name: "ChatGLM",
    handle: "chatglm",
    website: "https://chatglm.cn",
    description: "Open-source Chinese LLM family with strong bilingual performance.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 5,
    name: "InternLM",
    handle: "internlm",
    website: "https://internlm.intern-ai.org.cn",
    description: "Open-source foundation models from Shanghai AI Lab for research and development.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 6,
    name: "Yi (01.AI)",
    handle: "yi-01ai",
    website: "https://www.01.ai",
    description: "Open-source Yi models from 01.AI focused on strong reasoning and multilingual performance.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 7,
    name: "Baichuan",
    handle: "baichuan",
    website: "https://www.baichuan-ai.com",
    description: "Open-source Chinese LLMs for general-purpose and research use.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 8,
    name: "MiniCPM",
    handle: "minicpm",
    website: "https://openbmb.vercel.app",
    description: "Open-source small language models from OpenBMB for efficient deployment.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 9,
    name: "Jan",
    handle: "jan-ai",
    website: "https://jan.ai",
    description: "Open-source, offline ChatGPT alternative prioritizing privacy and customization.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 10,
    name: "Open WebUI",
    handle: "open-webui",
    website: "https://openwebui.com",
    description: "Open-source web UI for local and remote LLMs with chat, RAG, and plugin support.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 11,
    name: "LibreChat",
    handle: "librechat",
    website: "https://www.librechat.ai",
    description: "Open-source multi-LLM chat UI with tools, agents, and self-hosted support.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 12,
    name: "Chatbot UI",
    handle: "chatbot-ui",
    website: "https://chatbotui.com",
    description: "Open-source ChatGPT UI clone for chat workflows.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 13,
    name: "OpenChatKit",
    handle: "openchatkit",
    website: "https://openchatkit.net",
    description: "Open-source ChatGPT alternative toolkit for building chatbots.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 14,
    name: "OpenAssistantGPT",
    handle: "openassistantgpt",
    website: "https://www.openassistantgpt.io",
    description: "Open-source platform to build custom AI chatbot assistants.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 15,
    name: "n8n",
    handle: "n8n",
    website: "https://n8n.io",
    description: "Open-source workflow automation platform with AI integrations.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 16,
    name: "Flowise",
    handle: "flowise",
    website: "https://flowiseai.com",
    description: "Open-source no-code UI for building LLM apps and AI agents.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 17,
    name: "Langflow",
    handle: "langflow",
    website: "https://langflow.org",
    description: "Open-source visual builder for LLM apps and agent workflows.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 18,
    name: "Kilo",
    handle: "kilo-ai",
    website: "https://kilocode.ai",
    description: "Open-source AI coding assistant for VS Code, enhancing coding efficiency and automation.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 19,
    name: "Stable Diffusion",
    handle: "stable-diffusion",
    website: "https://stability.ai",
    description: "Stability AI develops open-source AI models for image, video, 3D, and audio generation.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 20,
    name: "Psychoroid",
    handle: "psychoroid-com",
    website: "https://psychoroid.com",
    description: "Open-source AI 3D engine for generating and customizing 3D assets from text and images.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 21,
    name: "hunyuan3d 2 0",
    handle: "hunyuan3d-2-0",
    website: "https://3d-models.hunyuan.tencent.com",
    description: "Open-source 3D asset generation model by Tencent.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 22,
    name: "Fiorino",
    handle: "fiorino-ai",
    website: "https://fiorinoai.tech",
    description: "Open-source AI cost management platform for SaaS businesses using LLMs.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 23,
    name: "Doublecloud With GPT 4",
    handle: "doublecloud-with-gpt-4",
    website: "https://double.cloud",
    description: "Platform for building sub-second analytics solutions using open-source technologies.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 24,
    name: "Evangeler List Of Affiliate Programs",
    handle: "evangeler-list-of-affiliate-programs",
    website: "https://evangeler.com",
    description: "Evangeler is an open-source platform listing affiliate programs for influencers to earn money.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 25,
    name: "Dify",
    handle: "dify-ai",
    website: "https://dify.ai",
    description: "Open-source LLMOps platform for building and operating generative AI applications.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 26,
    name: "Tiptap Editor 3 0 Beta",
    handle: "tiptap-editor-3-0-beta",
    website: "https://www.tiptap.dev",
    description: "Headless, open-source editor framework for building custom rich text editors with extensions and collaboration features.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 27,
    name: "Activepieces",
    handle: "activepieces",
    website: "https://www.activepieces.com",
    description: "AI-first automation platform; open-source alternative to Zapier and Workato for team workflows.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 28,
    name: "Coder",
    handle: "coder",
    website: "https://coder.com",
    description: "Self-hosted cloud development environment for developers and AI coding agents.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 29,
    name: "Agno",
    handle: "agno",
    website: "https://www.agno.com",
    description: "Open-source library for building fast, model-agnostic AI agents with memory and tools.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 30,
    name: "Qdrant",
    handle: "qdrant-io",
    website: "https://qdrant.io",
    description: "Open-source vector database and search engine for similarity search in AI applications.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 31,
    name: "Pearai",
    handle: "pearai",
    website: "https://trypear.ai",
    description: "Open-source AI code editor integrating AI tools for enhanced coding and project development.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 32,
    name: "Suna",
    handle: "suna",
    website: "https://www.suna.so",
    description: "Open-source AI assistant for research, data analysis, and task automation.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 33,
    name: "Superagi Cloud",
    handle: "superagi-cloud",
    website: "https://superagi.com",
    description: "Open-source platform to build, manage, and run autonomous AI agents.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 34,
    name: "Copilotkit",
    handle: "copilotkit",
    website: "https://www.copilotkit.ai",
    description: "CopilotKit integrates AI into apps with plug & play React components, open source and customizable.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 35,
    name: "Skyvern",
    handle: "skyvern",
    website: "https://www.skyvern.com",
    description: "Open-source AI agent for automating browser-based workflows using LLMs and Computer Vision.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 36,
    name: "Open Interpreter",
    handle: "open-interpreter",
    website: "https://openinterpreter.com",
    description: "Open-source tool enabling language models to run code on your computer.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 37,
    name: "Apipark",
    handle: "apipark",
    website: "https://apipark.com",
    description: "Open-source AI Gateway and Developer Portal for managing and deploying AI and API services.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 38,
    name: "Llmchat",
    handle: "llmchat",
    website: "https://llmchat.co",
    description: "AI-powered research platform with privacy and open-source focus.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 39,
    name: "Screenpipe",
    handle: "screenpipe",
    website: "https://screenpi.pe",
    description: "Open-source library for 24/7 screen and mic recording, connecting to LLMs for AI applications.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 40,
    name: "Laminar",
    handle: "laminar",
    website: "https://www.lmnr.ai",
    description: "Open-source platform for tracing and evaluating AI applications.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 41,
    name: "Langtrace",
    handle: "langtrace-ai",
    website: "https://www.langtrace.ai",
    description: "Open Source Observability and Evaluations Platform for AI Agents.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 42,
    name: "Patched",
    handle: "patched",
    website: "https://patched.codes",
    description: "Open-source framework for automating development workflows with custom AI workflows.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 43,
    name: "Rlama",
    handle: "rlama",
    website: "https://rlama.dev",
    description: "Open-source tool for building document question-answering systems with local AI models.",
    category: "Private AI",
    free: true,
    openSource: true,
    privacy: true,
  },
  {
    id: 44,
    name: "Devika",
    handle: "devika-ai",
    website: "https://devikaai.org",
    description: "Open-source AI software engineer that understands instructions, researches, and generates code.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 45,
    name: "Maxkb",
    handle: "maxkb",
    website: "https://maxkb.pro",
    description: "Open-source AI assistant for enterprise with RAG and LLM.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 46,
    name: "Pneumatic Workflow",
    handle: "pneumatic-workflow",
    website: "https://www.pneumatic.app",
    description: "Open-source workflow management platform with human-AI integration for business process automation.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 47,
    name: "Qubinets",
    handle: "qubinets",
    website: "https://qubinets.com",
    description: "Open-source platform simplifying AI and big data infrastructure deployment and management.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 48,
    name: "Blueprints",
    handle: "blueprints",
    website: "https://blueprints.mozilla.ai",
    description: "A hub for open-source AI workflows with pre-configured templates and resources.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 49,
    name: "AI Adventure",
    handle: "ai-adventure",
    website: "https://ai-adventure.steamship.com",
    description: "A gaming community and open-source system for AI-assisted narrative adventure games.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 50,
    name: "Qrev",
    handle: "qrev-ai",
    website: "https://qrev.ai",
    description: "Open-source AI agents to automate outbound sales and scale sales organizations.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 51,
    name: "Memoripy",
    handle: "memoripy",
    website: "https://memoripy.com",
    description: "Open-source AI memory layer for context-aware applications.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 52,
    name: "Ask On Data",
    handle: "ask-on-data",
    website: "https://AskOnData.com",
    description: "AI-powered, open source chat-based ETL tool for data engineering.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 53,
    name: "008",
    handle: "008",
    website: "https://008agent.ai",
    description: "Open-source VoIP phone with AI for call transcription, summarization, and CRM integration.",
    category: "AI for Audio & Voice",
    free: true,
    openSource: true,
  },
  {
    id: 54,
    name: "Octogen An Open Source Code Interpreter",
    handle: "octogen-an-open-source-code-interpreter",
    website: "https://octogen.dev",
    description: "Open-source code interpreter powered by GPT3.5/4 and CodeLlama for code solutions and local deployment.",
    category: "Private AI",
    free: true,
    openSource: true,
    privacy: true,
  },
  {
    id: 55,
    name: "Llmonitor",
    handle: "llmonitor",
    website: "https://llmonitor.com",
    description: "Open-source AI platform for LLM chatbot management, observability, and evaluation.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 56,
    name: "Jacob Just Another Coding Bot",
    handle: "jacob-just-another-coding-bot",
    website: "https://www.jacb.ai",
    description: "JACoB is an open-source AI coding agent that automates tasks and enhances code quality.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 57,
    name: "Hexabot",
    handle: "hexabot",
    website: "https://hexabot.io",
    description: "Open-source AI chatbot builder for creating and managing AI-powered chatbots.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 58,
    name: "Scourhead",
    handle: "scourhead",
    website: "https://scourhead.com",
    description: "Free, open-source AI agent for web data collection and spreadsheet organization.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 59,
    name: "Open Agent Kit Build Agents In Minutes",
    handle: "open-agent-kit-build-agents-in-minutes",
    website: "https://open-agent-kit.com",
    description: "Open-source platform for building, customizing, and deploying AI agents.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 60,
    name: "Matter",
    handle: "matter-ai",
    website: "https://matterai.dev",
    description: "Open-source AI Code Reviewer Agent for bug, security, and performance issue detection in code changes.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 61,
    name: "Magicanimate Playground",
    handle: "magicanimate-playground",
    website: "https://www.magicanimate.org",
    description: "Open-source project for creating animated videos from a single image and motion video.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 62,
    name: "Magi 1",
    handle: "magi-1",
    website: "https://magi-1.io",
    description: "Open-source AI video generator with chunk-wise prompting for consistent, controllable video creation.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 63,
    name: "Breveai",
    handle: "breveai",
    website: "https://breveai.com",
    description: "BreveAI: LLMs integrated with real-world data, focusing on efficiency and open-source adoption.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 64,
    name: "Chat With Media",
    handle: "chat-with-media",
    website: "https://www.aichatwithmedia.com",
    description: "Open-source software to chat with PDF files for easy research and understanding.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 65,
    name: "Iask",
    handle: "iask",
    website: "https://getiask.com",
    description: "iAsk is an open-source, private LLM frontend for answering questions about your files and links.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 67,
    name: "Replicate",
    handle: "replicate-ai",
    website: "https://replicate.com",
    description: "Cloud API to run, fine-tune, and deploy open-source machine learning models.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 68,
    name: "Civitai Green",
    handle: "civitai-green",
    website: "https://civitai.green",
    description: "A hub for open-source generative AI models and a community for AI art creators.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 69,
    name: "Pollinations",
    handle: "pollinations",
    website: "https://pollinations.ai",
    description: "Open-source platform providing easy-to-use AI text and image generation APIs.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 70,
    name: "Helicone",
    handle: "helicone-ai",
    website: "https://www.helicone.ai",
    description: "Open-source LLM observability platform for monitoring, debugging, and improving AI apps.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 71,
    name: "Deepseek R1",
    handle: "deepseek-r1",
    website: "https://deepseek-r1.com",
    description: "Access to DeepSeek R1, an open-source AI model for advanced reasoning.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 72,
    name: "Meilisearch",
    handle: "meilisearch",
    website: "https://www.meilisearch.com",
    description: "Open-source AI search engine for fast and relevant full-text searches.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 73,
    name: "Tolgee AI Translator",
    handle: "tolgee-ai-translator",
    website: "https://tolgee.io/features/autonomous-translation",
    description: "Open-source localization tool with AI translation, context awareness, and human review.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 74,
    name: "Flux 1 AI 1",
    handle: "flux-1-ai-1",
    website: "https://flux-1.ai",
    description: "Free, open-source AI image generator for rapid, high-quality image creation.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 75,
    name: "Kokoro Web",
    handle: "kokoro-web",
    website: "https://voice-generator.pages.dev",
    description: "Free and open-source online AI voice generator for text to speech conversion.",
    category: "AI for Audio & Voice",
    free: true,
    openSource: true,
  },
  {
    id: 76,
    name: "AI Flow",
    handle: "ai-flow",
    website: "https://ai-flow.net",
    description: "Open-source platform to connect and create AI workflows with a drag-and-drop interface.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 77,
    name: "Morphik",
    handle: "morphik",
    website: "https://www.morphik.ai",
    description: "Open-source AI knowledge base and research agent for enterprise data.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 78,
    name: "Tracardi",
    handle: "tracardi",
    website: "https://www.tracardi.com",
    description: "Open-source Customer Data Platform for automated customer engagement and personalized experiences.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 79,
    name: "Openkoda",
    handle: "openkoda",
    website: "https://openkoda.com",
    description: "Open-source platform for rapid development of business applications, especially in insurance.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 80,
    name: "Deepseek Online",
    handle: "deepseek-online",
    website: "https://www.deepseekv3.net",
    description: "Free online access to DeepSeek V3, a powerful open-source AI model.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 81,
    name: "Flojoy Studio",
    handle: "flojoy-studio",
    website: "https://www.flojoy.ai",
    description: "Open-source platform for hardware testing and automation with cloud connectivity.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 82,
    name: "Lakesail",
    handle: "lakesail",
    website: "https://lakesail.com",
    description: "Open-source Rust framework unifying stream, batch, and AI workloads for Big Data.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 83,
    name: "API Usage",
    handle: "api-usage",
    website: "https://apiusage.info",
    description: "Open-source tool to track and analyze OpenAI API usage and costs.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 84,
    name: "Sorawebui",
    handle: "sorawebui",
    website: "https://sorawebui.com",
    description: "Open-source web platform for generating videos from text using OpenAI's Sora model.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 85,
    name: "Aigur",
    handle: "aigur-dev",
    website: "https://aigur.dev",
    description: "Aigur: Open-source library for building and managing Generative AI applications with ease.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 86,
    name: "Yobulk",
    handle: "yobulk",
    website: "https://yobulk.dev",
    description: "AI-powered, open-source CSV importer for SaaS and standalone use.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 87,
    name: "Prst",
    handle: "prst-ai",
    website: "https://prst.ai",
    description: "Self-hosted AI automation tool for prompt management and AI model optimization.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 88,
    name: "The Complete Giude Of Mistral 7b",
    handle: "the-complete-giude-of-mistral-7b",
    website: "https://mistral-7b.com",
    description: "A powerful, open-source LLM with various fine-tuned models for specific applications.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 89,
    name: "Embedefy",
    handle: "embedefy",
    website: "https://www.embedefy.com",
    description: "Embedefy offers free, open-source embeddings for various AI applications within fair usage limits.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 90,
    name: "Chatgptsora",
    handle: "chatgptsora",
    website: "https://chatgptsora.co",
    description: "Open-source platform for creating videos from text using OpenAI's Sora model.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 91,
    name: "Pongo",
    handle: "pongo",
    website: "https://joinpongo.com",
    description: "Open-source visual language model for understanding images with text prompts.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 92,
    name: "Lite Queen",
    handle: "lite-queen",
    website: "https://litequeen.com",
    description: "Open-source SQLite database management software for your server.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 93,
    name: "Stable Audio Open",
    handle: "stable-audio-open",
    website: "https://stable-audio-open.com",
    description: "Open-source model for generating short audio samples and sound effects from text.",
    category: "AI for Audio & Voice",
    free: true,
    openSource: true,
  },
  {
    id: 94,
    name: "Domino",
    handle: "domino",
    website: "https://domino-workflows.io",
    description: "Open-source no-code platform for creating, managing, and deploying advanced data and A.I workflows.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 95,
    name: "Themog",
    handle: "themog",
    website: "http://themog.tech",
    description: "Open-source platform for AI-driven market analysis in emerging markets.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 96,
    name: "Volamail",
    handle: "volamail",
    website: "https://www.volamail.com",
    description: "Open-source email editor with AI assistance for easy email creation and sending.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 97,
    name: "Fluxpicture",
    handle: "fluxpicture",
    website: "https://www.fluxpicture.com",
    description: "Open-source AI image generation platform for fast, realistic image creation from text.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 98,
    name: "Backmesh",
    handle: "backmesh",
    website: "https://backmesh.com",
    description: "Open Source BaaS for AI apps to securely call LLM APIs without backend.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 99,
    name: "Open Source AI Gateway",
    handle: "open-source-ai-gateway",
    website: "https://ai-gateway.dev",
    description: "Open-source AI gateway for managing multiple LLM providers with built-in features.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 100,
    name: "Formsflow",
    handle: "formsflow",
    website: "https://formsflow.ai",
    description: "Open-source low-code platform for forms, workflow automation, and analytics.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 101,
    name: "Opensilver",
    handle: "opensilver",
    website: "https://opensilver.net",
    description: "Open-source UI framework for .NET web apps",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 102,
    name: "Adminforth",
    handle: "adminforth",
    website: "https://adminforth.dev",
    description: "Open-source Tailwind admin panel framework with Vue3 and Node.js Typescript support.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 103,
    name: "AI Assisted Contember Studio",
    handle: "ai-assisted-contember-studio",
    website: "https://www.contember.com",
    description: "Contember: rapid backend development with AI, TypeScript, and open-source framework.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 104,
    name: "Stablecog",
    handle: "stablecog",
    website: "https://stablecog.com",
    description: "Stablecog is a free and open-source AI image generator using Stable Diffusion and Kandinsky.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 105,
    name: "Thinkdiffusion",
    handle: "thinkdiffusion",
    website: "https://www.thinkdiffusion.com/",
    description: "Cloud platform for open-source generative AI art and video tools.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 106,
    name: "Distillery By Followfox",
    handle: "distillery-by-followfox",
    website: "https://followfox.ai",
    description: "Open-source AI text-to-image generator built over Stable Diffusion.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 107,
    name: "Mygptreader",
    handle: "mygptreader",
    website: "https://www.myreader.io",
    description: "Open-source Slack bot for summarizing content and voice communication.",
    category: "AI for Audio & Voice",
    free: true,
    openSource: true,
  },
  {
    id: 108,
    name: "Epigram",
    handle: "epigram",
    website: "https://epigram.news",
    description: "Open-source, AI-powered news app for bite-sized summaries and personalized news.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 109,
    name: "Argpt For Monocle",
    handle: "argpt-for-monocle",
    website: "https://brilliant.xyz",
    description: "Open-source ecosystem building AR glasses with generative AI capabilities for developers and creatives.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 110,
    name: "Amurex",
    handle: "amurex",
    website: "https://www.amurex.ai",
    description: "Open-source AI unifying workflow, connecting knowledge, and automating tasks.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 111,
    name: "Voiceink",
    handle: "voiceink",
    website: "https://tryvoiceink.com",
    description: "Opensource voice-to-text macOS app with local AI for privacy and offline use.",
    category: "AI for Audio & Voice",
    free: true,
    openSource: true,
  },
  {
    id: 112,
    name: "Chatpad",
    handle: "chatpad-ai",
    website: "https://chatpad.ai",
    description: "Free, open-source ChatGPT UI focused on privacy and user experience.",
    category: "Private AI",
    free: true,
    openSource: true,
    privacy: true,
  },
  {
    id: 113,
    name: "Sanctum",
    handle: "sanctum-ai",
    website: "https://sanctum.ai",
    description: "Private, local AI assistant for secure AI conversations using open-source models.",
    category: "Private AI",
    free: true,
    openSource: true,
    privacy: true,
  },
  {
    id: 114,
    name: "Design System",
    handle: "design-system",
    website: "https://www.kickstartds.com",
    description: "Open Source Design System starter kit with UI toolkit, component library, and AI assistant.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 115,
    name: "Todovex",
    handle: "todovex",
    website: "https://www.todovex.ai",
    description: "Open Source AI-Powered Todoist Clone for task organization and prediction.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 116,
    name: "Webdb",
    handle: "webdb",
    website: "https://webdb.app",
    description: "Open-source database IDE with modern features and multi-database support.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 117,
    name: "Llama 3",
    handle: "llama-3",
    website: "https://llama3.dev",
    description: "Meta's latest open-source language model and chatbot.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 118,
    name: "Cybertraceai",
    handle: "cybertraceai",
    website: "https://cybertraceai.com",
    description: "Open-source AI agent simplifying network management with natural language interactions.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 119,
    name: "Plexo",
    handle: "plexo",
    website: "https://plexo.app",
    description: "Open-source, AI-powered project management platform for streamlined team collaboration.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 120,
    name: "Aurora Terminal Agent",
    handle: "aurora-terminal-agent",
    website: "https://aurora.the-box.dev",
    description: "Free, open-source AI assistant for easier terminal interaction with smart command suggestions.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 121,
    name: "Reflection 70b",
    handle: "reflection-70b",
    website: "https://reflection70b.net",
    description: "Open-source AI model based on Llama 70B, surpassing GPT-4 with self-correction.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 122,
    name: "Prompto",
    handle: "prompto",
    website: "https://prompto.asanchez.dev",
    description: "Open-source web app for interacting with LLMs, fine-tuning results, and saving prompts.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 123,
    name: "Gnothi",
    handle: "gnothi",
    website: "https://gnothiai.com",
    description: "Open-source AI journal providing insights and resources using AI.",
    category: "AI Journaling & Notes",
    free: true,
    openSource: true,
  },
  {
    id: 124,
    name: "Rapid",
    handle: "rapid-ai",
    website: "https://rapidai.tech",
    description: "Open-source AI organization focusing on engineering implementation of AI models.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 125,
    name: "Deeplivecam",
    handle: "deeplivecam",
    website: "https://deeplivecam.net",
    description: "Open-source AI tool for real-time face swaps and avatar creation for VTubers and streamers.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 126,
    name: "Pygmalion",
    handle: "pygmalion-ai",
    website: "https://pygmalion.chat",
    description: "Open-source AI project for chat, role-play, and character creation.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 127,
    name: "AI Tamago",
    handle: "ai-tamago",
    website: "https://ai-tamago.fly.dev",
    description: "A local, free, open-source AI Tamagotchi featuring Peanut the Squirrel.",
    category: "Private AI",
    free: true,
    openSource: true,
    privacy: true,
  },
  {
    id: 128,
    name: "Vizzy",
    handle: "vizzy",
    website: "https://vizzy.rbren.io",
    description: "Open-source tool for rapid data visualization using ChatGPT.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 129,
    name: "Reachat",
    handle: "reachat",
    website: "https://reachat.dev",
    description: "Open-source ReactJS UI library for building LLM and ChatUIs quickly.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 130,
    name: "Mimicpc",
    handle: "mimicpc-ai",
    website: "https://www.mimicpc.com/",
    description: "Open-source AI platform with customizable AI tools and models.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 131,
    name: "Continue",
    handle: "continue",
    website: "https://continue.dev",
    description: "Open-source AI code assistant for customizable autocomplete and chat experiences in IDEs.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 132,
    name: "Chattyui",
    handle: "chattyui",
    website: "https://chattyui.com",
    description: "Open-source Gemini/ChatGPT-like interface for local browser-based open-source models.",
    category: "Private AI",
    free: true,
    openSource: true,
    privacy: true,
  },
  {
    id: 133,
    name: "Snowbrain",
    handle: "snowbrain",
    website: "https://snowbrain.dev",
    description: "An AI-driven, open-source data analyst prototype for Snowflake data insights.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 134,
    name: "Botticellibots",
    handle: "botticellibots",
    website: "https://botticellibots.com",
    description: "Open-source .NET Core framework for building universal bots with AI and database integration.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 135,
    name: "Promptcraft",
    handle: "promptcraft",
    website: "https://promptcraft.swishjam.com",
    description: "Open-source AI prompt builder for crafting effective chatbot prompts.",
    category: "AI Agents & Automation",
    free: true,
    openSource: true,
  },
  {
    id: 136,
    name: "Tavonnai",
    handle: "tavonnai",
    website: "https://tavonnai.com",
    description: "Platform with 30+ open-source LLMs for chat, image, and video generation with unlimited usage.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 137,
    name: "Repobase",
    handle: "repobase",
    website: "https://www.repobase.co",
    description: "RepoBase analyzes open-source projects to identify promising investment opportunities using AI.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 138,
    name: "Bagel",
    handle: "bagel",
    website: "https://bagel-ai.org",
    description: "Open-source unified multimodal AI for understanding, generation, editing.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 139,
    name: "Aieditor",
    handle: "aieditor",
    website: "https://aieditor.dev",
    description: "Open-source AI-powered rich text editor with Markdown support and private deployment.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 140,
    name: "Refiner",
    handle: "refiner",
    website: "https://refiner.dev",
    description: "AI-powered open-source code refactoring and generation service.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 141,
    name: "Samaritanai",
    handle: "samaritanai",
    website: "https://www.samaritanai.xyz",
    description: "AI tool visualizing codebases as network graphs, aiding open-source contributions.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 142,
    name: "Libswitch",
    handle: "libswitch",
    website: "https://libswitch.dev",
    description: "LibSwitch is an AI-powered open-source tool for code conversion between libraries.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 143,
    name: "Papertlab From Papert In",
    handle: "papertlab-from-papert-in",
    website: "https://papert.in",
    description: "Opensource AI pair programmer for code editing and AI-assisted development.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 144,
    name: "Crackcoder",
    handle: "crackcoder",
    website: "https://crackcoder.live",
    description: "Open-source AI tool for solving DSA questions undetectably during tech interviews.",
    category: "AI for Career",
    free: true,
    openSource: true,
  },
  {
    id: 145,
    name: "Gunbot",
    handle: "gunbot-com",
    website: "https://www.gunbot.com",
    description: "Self-hosted crypto trading bot for automated trading on multiple exchanges with privacy.",
    category: "AI for Trading",
    free: true,
    openSource: true,
  },
  {
    id: 146,
    name: "Components",
    handle: "components-ai",
    website: "https://components.ai",
    description: "Open-source design tool for building custom design tools without code.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 147,
    name: "Lilac",
    handle: "lilac",
    website: "https://lilacml.com",
    description: "Open-source tool for data and AI practitioners to improve data quality for LLMs.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 148,
    name: "Learnhouse",
    handle: "learnhouse",
    website: "https://learnhouse.app",
    description: "Open-source learning platform for creating and delivering online courses and training programs.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 149,
    name: "Recontent",
    handle: "recontent-app",
    website: "https://recontent.app",
    description: "Open-source product copy & localization tool for product teams.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 150,
    name: "Learn Prompting",
    handle: "learn-prompting",
    website: "https://learnprompting.org",
    description: "Free, open-source course for learning prompt engineering and AI communication.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 151,
    name: "Oss Insight",
    handle: "oss-insight",
    website: "https://ossinsight.io",
    description: "Open Source Software insight tool analyzing GitHub events with natural language querying.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 152,
    name: "Constellab",
    handle: "constellab",
    website: "https://constellab.io",
    description: "Open-source AI and data platform for life sciences, enabling secure data processing and collaboration.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 153,
    name: "Langui",
    handle: "langui",
    website: "https://www.LangUI.dev",
    description: "Open Source Tailwind CSS components for AI and GPT projects.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 154,
    name: "AI UX Patterns",
    handle: "ai-ux-patterns",
    website: "https://aiux.rezza.io",
    description: "An opensource collection of UX patterns for AI products, helping builders create intuitive AI experiences.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 155,
    name: "Chartdb",
    handle: "chartdb",
    website: "https://chartdb.io",
    description: "Free, open-source database diagram editor with AI-powered DDL script generation.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 156,
    name: "Hugging Face",
    handle: "hugging-face",
    website: "https://huggingface.co",
    description: "AI community platform for open-source ML models, datasets, and applications.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 157,
    name: "Airbyte",
    handle: "airbyte",
    website: "https://airbyte.com",
    description: "Open-source data integration platform for ELT, replication, and AI-ready data.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 158,
    name: "Label Studio",
    handle: "label-studio",
    website: "https://labelstud.io",
    description: "Open source data labeling tool for various data types and M/L integration.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 159,
    name: "Mindspore",
    handle: "mindspore-cn",
    website: "https://mindspore.cn",
    description: "Huawei's open-source AI framework for full-scenario deep learning.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 160,
    name: "Huntr",
    handle: "huntr-com",
    website: "https://huntr.com",
    description: "Bug bounty platform for AI/ML open-source apps, libraries, and model file formats.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 161,
    name: "Calcforge",
    handle: "calcforge",
    website: "https://calcforge.com",
    description: "Open-source engineering calculators and collaboration platform for civil, mechanical, and electrical professionals.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 162,
    name: "Metaflow",
    handle: "metaflow-org",
    website: "https://metaflow.org",
    description: "Open-source framework for building and managing ML, AI, and data science projects.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 163,
    name: "Spice",
    handle: "spice-ai",
    website: "https://spice.ai",
    description: "Open-source data and AI platform for building intelligent software with Web3 data.",
    category: "Web3 & Blockchain",
    free: true,
    openSource: true,
    blockchain: true,
    web3: true,
  },
  {
    id: 164,
    name: "Openlit",
    handle: "openlit",
    website: "https://openlit.io",
    description: "Open-source GenAI/LLM observability platform with APM, native to OpenTelemetry.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 165,
    name: "Aigrant",
    handle: "aigrant-org",
    website: "https://aigrant.org",
    description: "Grants for open source AI projects, providing compute or cash.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 166,
    name: "Nat",
    handle: "nat-dev",
    website: "https://nat.dev",
    description: "Open-source playground for testing and evaluating LLMs.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 167,
    name: "Tilemaker",
    handle: "tilemaker",
    website: "https://tilemaker.app",
    description: "Free, open-source AI app for creating seamless tiled images.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 168,
    name: "Resume Matcher",
    handle: "resume-matcher",
    website: "https://www.resumematcher.fyi",
    description: "Free, open-source tool to tailor resumes using NLP and data insights.",
    category: "AI for Career",
    free: true,
    openSource: true,
  },
  {
    id: 169,
    name: "Makr Io 15 Web Apps In 30 Days",
    handle: "makr-io-15-web-apps-in-30-days",
    website: "https://makr.io",
    description: "A collection of 15 open-source web apps built with AI in 30 days.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 170,
    name: "Embedditor",
    handle: "embedditor",
    website: "https://embedditor.ai",
    description: "Open-source editor for vector LLM embeddings to improve search and reduce costs.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 171,
    name: "Markup Document Annotation",
    handle: "markup-document-annotation",
    website: "https://www.getmarkup.com",
    description: "Open-source annotation tool for transforming unstructured documents into structured data.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 172,
    name: "Thepanel",
    handle: "thepanel",
    website: "https://thepanel.dev",
    description: "Open-source analytics platform for web and mobile apps, offering Mixpanel alternative.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 173,
    name: "Lumina",
    handle: "lumina-ai",
    website: "https://luminaai.tech",
    description: "Open-source AI platform with chatbot, image, code, video, and music features.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 174,
    name: "Zetane",
    handle: "zetane-com",
    website: "https://zetane.com",
    description: "Zetane offers an open-source AI platform for developing transparent and reliable AI solutions in high-risk industries.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 175,
    name: "Languagegui",
    handle: "languagegui",
    website: "https://languagegui.com",
    description: "Open-source UI Kit for LLMs to format text outputs into richer GUIs.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 176,
    name: "Dvc",
    handle: "dvc-ai",
    website: "https://dvc.ai",
    description: "Open-source version control for data science and machine learning projects.",
    category: "AI for Research",
    free: true,
    openSource: true,
  },
  {
    id: 177,
    name: "Eyegestures",
    handle: "eyegestures",
    website: "https://eyegestures.com",
    description: "Open-source gaze tracking using webcams for accessible interfaces and eye-tracking studies.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 178,
    name: "Contribhub",
    handle: "contribhub",
    website: "https://contribhub.com",
    description: "A platform to find and contribute to open source projects.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 179,
    name: "Autoarena",
    handle: "autoarena",
    website: "https://www.autoarena.app",
    description: "Open-source tool for automated head-to-head evaluation of GenAI systems using LLM judges.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 180,
    name: "Bakery By Bagel",
    handle: "bakery-by-bagel",
    website: "https://bakery.dev",
    description: "Platform to fine-tune and monetize open-source AI models with one click.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 181,
    name: "Mutatio",
    handle: "mutatio-dev",
    website: "https://mutatio.dev",
    description: "A free, open-source platform for AI prompt engineering, testing, and optimization.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 182,
    name: "Chattts Site",
    handle: "chattts-site",
    website: "https://www.chattts.site",
    description: "Open-source text-to-speech project for realistic dialogue generation.",
    category: "AI for Audio & Voice",
    free: true,
    openSource: true,
  },
  {
    id: 183,
    name: "Overwatch Data",
    handle: "overwatch-data",
    website: "https://overwatchdata.ai",
    description: "AI-driven platform for tailored news and social insights, focusing on open-source intelligence.",
    category: "AI for Search & News",
    free: true,
    openSource: true,
  },
  {
    id: 184,
    name: "Opnform",
    handle: "opnform",
    website: "https://opnform.com",
    description: "Open-source platform with an AI form builder to create forms and surveys for free.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 185,
    name: "Webposter Lab",
    handle: "webposter-lab",
    website: "https://webposterlab.com",
    description: "Open-source AI poster generator for websites.",
    category: "AI Website Builders",
    free: true,
    openSource: true,
  },
  {
    id: 186,
    name: "Monai",
    handle: "monai-io",
    website: "https://monai.io",
    description: "Open-source framework for healthcare imaging AI development and deployment.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 187,
    name: "Quenti",
    handle: "quenti",
    website: "https://quenti.io",
    description: "Quenti is a free, open-source learning platform with flashcards, games, and study tools.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 188,
    name: "Flux AI Image Generator With Flux 1",
    handle: "flux-ai-image-generator-with-flux-1",
    website: "https://fluxai.dev",
    description: "Open-source AI image generation tool with various models for diverse creative needs.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 189,
    name: "Staticblocks",
    handle: "staticblocks",
    website: "https://staticblocks.com",
    description: "AI-powered, self-hosted static website builder with drag-and-drop interface and no coding required.",
    category: "AI Website Builders",
    free: true,
    openSource: true,
  },
  {
    id: 190,
    name: "Swiftsora",
    handle: "swiftsora",
    website: "https://www.swiftsora.com",
    description: "Open-source AI video generator using OpenAI's Sora model with easy deployment.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 191,
    name: "Frigate Nvr",
    handle: "frigate-nvr",
    website: "https://frigate.video",
    description: "Open-source NVR with local AI object detection for IP cameras.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 192,
    name: "Classroomio",
    handle: "classroomio",
    website: "https://classroomio.com",
    description: "Open source LMS for creating, managing, and delivering courses with AI support.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 193,
    name: "Countless",
    handle: "countless-dev",
    website: "https://countless.dev",
    description: "A free, open-source platform to compare AI models from different providers.",
    category: "Developer APIs",
    free: true,
    openSource: true,
  },
  {
    id: 194,
    name: "Public Prompts",
    handle: "public-prompts",
    website: "https://publicprompts.art",
    description: "A collection of free, open-source prompts, models, and embeddings for image generation.",
    category: "Image Generation",
    free: true,
    openSource: true,
  },
  {
    id: 195,
    name: "Hunyuan Video",
    handle: "hunyuan-video",
    website: "https://hunyuanvideoai.com",
    description: "Open-source AI video generator by Tencent, creating high-quality videos from text.",
    category: "AI for YouTube/Video",
    free: true,
    openSource: true,
  },
  {
    id: 196,
    name: "Harmonai",
    handle: "harmonai",
    website: "https://www.harmonai.org",
    description: "Harmonai is an open-source generative audio tool for accessible music production.",
    category: "AI for Audio & Voice",
    free: true,
    openSource: true,
  },
  {
    id: 197,
    name: "Usethisprompt",
    handle: "usethisprompt",
    website: "https://usethisprompt.io",
    description: "A free, open-source platform for sharing and discussing productivity-focused AI prompts.",
    category: "AI for Everyday Tasks",
    free: true,
    openSource: true,
  },
  {
    id: 198,
    name: "Text Generator Plugin",
    handle: "text-generator-plugin",
    website: "https://text-gen.com",
    description: "Open-source AI tool for knowledge creation and organization in Obsidian.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
  {
    id: 199,
    name: "Freenote",
    handle: "freenote",
    website: "https://freenote.app",
    description: "Open-source AI journal app with local storage for privacy and easy note management.",
    category: "AI Journaling & Notes",
    free: true,
    openSource: true,
  },
  {
    id: 200,
    name: "Text Snap",
    handle: "text-snap",
    website: "https://www.textsnap.app",
    description: "AI-powered open-source tool for accurate text formatting and efficient user actions.",
    category: "AI Writing & Editing",
    free: true,
    openSource: true,
  },
];

export const categories = [
  "All",
  "AI for Everyday Tasks",
  "AI for Research",
  "AI Agents & Automation",
  "AI for Search & News",
  "AI Writing & Editing",
  "AI for YouTube/Video",
  "AI for Audio & Voice",
  "Image Generation",
  "AI Website Builders",
  "AI Journaling & Notes",
  "Developer APIs",
  "Private AI",
  "Web3 & Blockchain",
  "AI for Career",
  "AI for Trading",
];
